version: '3'

services:
  server:
    container_name: drash_server
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.2.3
    volumes:
      - ./src/server:/var/www/server
    working_dir: /var/www/server
    ports:
      - "1667:1667"
    command: bash -c "deno run --allow-net --allow-read --allow-env app.ts"
    networks:
      - chatsterisk-app-network

  asterisk:
    container_name: asterisk_pbx
    image: hibou/asterisk:14
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "16384-16394:16384-16394/udp"
      - "8088:8088"
      - "8089:8089"
    volumes:
      - "./.docker/config/asterisk/sip.conf:/etc/asterisk/sip.conf"
      - "./.docker/config/asterisk/extensions.conf:/etc/asterisk/extensions.conf"
      - "./.docker/config/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf"
      - "./.docker/config/asterisk/rtp.conf:/etc/asterisk/rtp.conf"
    labels:
      - "traefik.enable=false"
#    networks:
#      default:
#        ipv4_address: 10.1.2.10

  ami:
    container_name: sip_ami
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.0.0
    volumes:
      - ./src/ami:/var/www/ami
    working_dir: /var/www/ami
    command: bash -c "deno run --allow-net app.ts"
    networks:
      - chatsterisk-app-network
    ports:
      - "1668:1668"

networks:
  chatsterisk-app-network:
    driver: bridge
#  default:
#    ipam:
#      config:
#        - subnet: 10.1.2.0/24