version: '3'

services:

  server:
    container_name: drash_server
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.5.4
    environment:
      USE_DENON: "true"
    volumes:
      - ./src/server:/var/www/server
    working_dir: /var/www/server
    ports:
      - "1667:1667"
    networks:
      - chatsterisk-app-network

  sip_socket:
    container_name: sip_socket
    depends_on:
      - asterisk
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.5.4
    environment:
      USE_DENON: "true"
    ports:
      - "1668:1668"
    volumes:
    - "./src/sip_socket:/var/www/sip_socket"
    working_dir: /var/www/rtc_socket
    networks:
      - chatsterisk-app-network

  rtc_socket:
    container_name: rtc_socket
    depends_on:
      - asterisk
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.5.4
    environment:
      USE_DENON: "true"
    ports:
      - "1669:1669"
    volumes:
      - "./src/rtc_socket:/var/www/rtc_socket"
    working_dir: /var/www/rtc_socket
    networks:
      - chatsterisk-app-network

  chat_socket:
    container_name: chat_socket
    depends_on:
      - asterisk
    build:
      context: .
      dockerfile: .docker/deno.dockerfile
      args:
        DENO_VERSION: 1.5.4
    environment:
      USE_DENON: "true"
    ports:
      - "1667:1667"
    volumes:
      - "./src/sip_socket:/var/www/chat_socket"
    working_dir: /var/www/chat_socket
    networks:
      - chatsterisk-app-network

  asterisk:
    container_name: asterisk_pbx
    image: hibou/asterisk:14
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "16384-16394:16384-16394/udp"
      - "8088:8088"
      - "8089:8089"
      - "5038:5038" # asterisk ami (manager.conf)
    volumes:
      - "./.docker/config/asterisk/sip.conf:/etc/asterisk/sip.conf"
      - "./.docker/config/asterisk/extensions.conf:/etc/asterisk/extensions.conf"
     # - "./.docker/config/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf"
      - "./.docker/config/asterisk/rtp.conf:/etc/asterisk/rtp.conf"
      - "./.docker/config/asterisk/manager.conf:/etc/asterisk/manager.conf"
    labels:
      - "traefik.enable=false"
#    networks:
#      default:
#        ipv4_address: 10.1.2.10
    networks:
      - chatsterisk-app-network

networks:
  chatsterisk-app-network:
    driver: bridge
#  default:
#    ipam:
#      config:
#        - subnet: 10.1.2.0/24