name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Run Server Tests
        run: cd src/server && deno test -A

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: cd src/server && deno fmt --check

      - name: linter
        run: cd src/server && deno lint --unstable