name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Run Server Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec drash_server deno test -A

      - name: Run Chat Socket Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec chat_socket deno test -A

      - name: Run RTC Socket Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec rtc_socket deno test -A

      - name: Run Chat Socket Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec chat_socket deno test -A

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check

      - name: linter
        run: deno lint --unstable --ignore='src/server/public'