name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  server_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Run Server Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec drash_server deno test -A

  chat_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Run Chat Socket Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec chat_socket deno test -A

  video_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Run Video Socket Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec video_socket deno test -A

  call_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Run Call Socket Tests
        run: |
          docker-compose up -d
          sleep 20
          docker exec call_socket deno test -A

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check

      - name: linter
        run: deno lint --unstable --ignore='src/server/public'